// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsService.Context;

namespace ProductsService.Migrations
{
    [DbContext(typeof(ProductApiContext))]
    partial class ProductApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductsService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wobbler, mini, grön",
                            ImageURL = "https://www.happyangler.se/i/hkg/022677210766_1/rapala-ultra-light-crank-3-cm-wobbler.jpg?$flyout$",
                            Name = "Wobbler",
                            Price = 59.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "rapala Shadow, 3-pack, 11 cm, olikfärgade",
                            ImageURL = "https://www.sportfiskeprylar.se/bilder/artiklar/zoom/SHADOWKIT2_1.jpg",
                            Name = "Rapala Shadow, 3-pack",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Spinnare, 3-pack, svart, silver, koppar",
                            ImageURL = "https://bojdaspon.se/wp-content/uploads/2020/01/Abu-Droppen-Spinnare-3-Pack.jpg",
                            Name = "Spinnare, 3-pack",
                            Price = 79.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hi-Lo Wobbler, Abu Garcia, 11 cm",
                            ImageURL = "https://www.happyangler.se/i/hkg/036282948877_1/abu-garcia-hi-lo-flytande-11-cm-wobbler.jpg",
                            Name = "Abu Garcia Hi-Lo Wobbler",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fjäderjiggar, Tungsten, 5-pack, olikfärgade",
                            ImageURL = "https://cdn.shopify.com/s/files/1/1218/2078/products/Untitled_design_3_1024x1024.png?v=1508789934",
                            Name = "Fjäderjiggar 5-pack",
                            Price = 129.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fiskelina, nylon, Stroft, 100m, 0.25 diam, 6.40kg",
                            ImageURL = "https://fiskedags.se/5961-large_default/stroft-nylon-fiskelina.jpg",
                            Name = "Stroft Fiskelina, nylon",
                            Price = 59.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fiskelina, flätad, Berkely FireLine, 110m, 0.12 diam, 10.20kg",
                            ImageURL = "https://www.jula.se/globalassets/catalog/productimages/722130.jpg?width=458&height=458&scale=both&bgcolor=white",
                            Name = "FireLine, flätad",
                            Price = 145.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Fiskespö, teleskop, 1.8-3.6m, kolfiber",
                            ImageURL = "https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/5A/7A/07658788-500d-4359-923a-ba88e4864376.jpg",
                            Name = "Leo GT400, teleskopspö",
                            Price = 549.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Pimpelspö, mini, ultralätt",
                            ImageURL = "https://i5.walmartimages.com/asr/8605a207-3410-44a1-93d9-b4eef11b9682_1.2cc67ccd8c20b9016c1e9a5c91d4bea7.jpeg",
                            Name = "Pimpelspö, mini",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fiskehåv, 54x28cm",
                            ImageURL = "https://shop.kvibergs.se/wp-content/uploads/2017/11/1519.jpg",
                            Name = "Fiskehåv",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Fiskevåg, Berkley, digital, max 23kg",
                            ImageURL = "https://www.jula.se/globalassets/catalog/productimages/771026.jpg?width=458&height=458&scale=both&bgcolor=white",
                            Name = "Berkley Fiskevåg",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Fiskekniv, Rapala, 4\"",
                            ImageURL = "https://www.batofiske.se/pub_images/large/02646_1013.jpg",
                            Name = "Rapala Fiskekniv",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Abu Garcia Spinnare, 12g, Reflex, Röd",
                            ImageURL = "https://www.happyangler.se/i/hkg/036282342743_1/abu-reflex-red-12-g-spinnare.jpg?$flyout$",
                            Name = "Abu Garcia Spinnare",
                            Price = 59.00m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Skeddrag, Toby, Abu Garcia 3-pack, olikfärgade",
                            ImageURL = "https://www.happyangler.se/i/hkg/036282852020_1/abu-garcia-toby-3-pack-skeddragset.jpg?$flyout$",
                            Name = "Toby Skeddrag 3-pack",
                            Price = 59.00m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Fiskelåda med 3 uppfällbara sorteringsfack, snäpplås, uppfällbart handtag",
                            ImageURL = "https://www.jula.se/globalassets/catalog/productimages/770028b.jpg?width=458&height=458&scale=both&bgcolor=white",
                            Name = "Fiskelåda",
                            Price = 199.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
